<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'Kontoinformationen',
    'Action' => 'Aktion',
    'Add to Cart' => 'In den Warenkorb legen',
    'Address' => 'Adresse',
    'Address information' => 'Adresse',
    'Are you sure you want to remove this product from cart?' => 'Möchten Sie dieses Produkt wirklich aus dem Warenkorb entfernen?',
    'Auth Key' => 'Authentifizierungsschlüssel',
    'Cart' => 'Wagen',
    'Checkout' => 'Kasse',
    'City' => 'Stadt',
    'Country' => 'Land',
    'Created At' => 'Hergestellt in',
    'Created by' => 'Erstellt von',
    'Created_at' => 'Hergestellt in',
    'Delete' => 'Löschen',
    'Description' => 'Beschreibung',
    'Email' => 'Email',
    'Firstname' => 'Vorname',
    'I' => 'Aber',
    'ID' => 'ID',
    'If you forgot your password you can {0}' => 'Wenn Sie Ihr Passwort vergessen haben, können Sie {0}',
    'Image' => 'Bild',
    'Is Admin ?' => 'Ist Administrator ?',
    'Lastname' => 'Nachname',
    'Login' => 'Anmeldung',
    'Logout' => 'Ausloggen',
    'Name' => 'Name',
    'Need new verification email?' => 'Benötigen Sie eine neue Bestätigungs-E-Mail?',
    'Next' => 'Nächste',
    'Order ID' => 'Befehl ID',
    'Order Summary' => 'Bestellübersicht',
    'Password' => 'Passwort',
    'Password Hash' => 'Passwort-Hash',
    'Password Repeat' => 'Passwort wiederholen',
    'Password Reset Token' => 'Token zum Zurücksetzen des Passworts',
    'Paypal Order ID' => 'Paypal-Bestell-ID',
    'Please choose your new password:' => 'Bitte wählen Sie Ihr neues Passwort:',
    'Please contact us if you think this is server error. Thank you.' => 'Bitte kontaktieren Sie uns, wenn Sie glauben, dass dies ein Serverfehler ist. Danke schön.',
    'Please fill out the following fields to login' => 'Bitte füllen Sie die folgenden Felder aus, um sich anzumelden',
    'Please fill out the following fields to signup:' => 'Bitte füllen Sie die folgenden Felder aus, um sich anzumelden:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Bitte füllen Sie Ihre E-Mail aus. Dort wird ein Link zum Zurücksetzen des Passworts gesendet.',
    'Please fill out your email. A verification email will be sent there.' => 'Bitte füllen Sie Ihre E-Mail aus. Dort wird eine Bestätigungs-E-Mail gesendet.',
    'Prev' => 'Zurück',
    'Price' => 'Preis',
    'Product' => 'Produkt',
    'Product ID' => 'Produkt ID',
    'Product Image' => 'Produkt Bild',
    'Product Name' => 'Produkt Name',
    'Products' => 'Produkte',
    'Profile' => 'Profil',
    'Published' => 'Veröffentlicht',
    'Quantity' => 'Menge',
    'Remember Me' => 'Behalte mich in Erinnerung',
    'Resend' => 'Erneut senden',
    'Save' => 'Speichern',
    'Send' => 'Senden',
    'Signup' => 'Anmelden',
    'State' => 'Zustand',
    'Status' => 'Status',
    'Thanks for your business' => 'Danke für dein Geschäft',
    'The above error occurred while the Web server was processing your request' => 'Der obige Fehler ist aufgetreten, während der Webserver Ihre Anfrage verarbeitet hat',
    'There are no items in the cart' => 'Es befinden sich keine Artikel im Warenkorb',
    'Total Items' => 'Gesamtanzahl',
    'Total Price' => 'Gesamtpreis',
    'Transaction ID' => 'Transaktions-ID',
    'Unit Price' => 'Stückpreis',
    'Update' => 'Aktualisieren',
    'Update account' => 'Account aktualisieren',
    'Update At' => 'Aktualisieren um',
    'Update By' => 'Aktualisieren von',
    'Update_by' => 'Update_by',
    'User ID' => 'Benutzeridentifikation',
    'Username' => 'Nutzername',
    'Verification Token' => 'Verifizierungstoken',
    'Welcome {0}' => 'Willkommen {0}',
    'Your account successfully updated' => 'Ihr Konto wurde erfolgreich aktualisiert',
    'Your address successfully updated' => 'Ihre Adresse wurde erfolgreich aktualisiert',
    'Your cart items' => 'Ihre Warenkorbartikel',
    'ZipCode' => 'Postleitzahl',
    'Zipcode' => 'Postleitzahl',
    'reset it' => 'Setzen Sie es zurück',
];
