<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'Hisob ma`lumotlari',
    'Action' => 'Harakat',
    'Add to Cart' => 'Savatga qo`shish',
    'Address' => 'Manzil',
    'Address information' => 'Manzil ma`lumoti',
    'Are you sure you want to remove this product from cart?' => 'Haqiqatan ham bu mahsulotni savatdan olib tashlamoqchimisiz?',
    'Auth Key' => 'Auth kaliti',
    'Cart' => 'Savatcha',
    'Checkout' => 'Tekshirib ko`rmoq',
    'City' => 'Shahar',
    'Country' => 'Mamlakat',
    'Created At' => 'Yaratilgan',
    'Created by' => 'Dasturchi',
    'Created_at' => 'Created_at',
    'Delete' => 'O`chirish',
    'Description' => 'Izoh',
    'Email' => 'Email',
    'Firstname' => 'Ism',
    'I' => 'Men',
    'ID' => 'ID',
    'If you forgot your password you can {0}' => 'Agar parolingizni unutgan boʻlsangiz, {0} mumkin',
    'Image' => 'Rasm',
    'Is Admin ?' => 'Adminmisiz ?',
    'Lastname' => 'Familiya',
    'Login' => 'Kirish',
    'Logout' => 'Chiqish',
    'Name' => 'Ism',
    'Need new verification email?' => 'Tasdiqlash uchun yangi pochta habari kerakmi?',
    'Next' => 'Keyingi',
    'Order ID' => 'Buyurtma ID',
    'Order Summary' => 'Buyurtma xulosasi',
    'Password' => 'Parol',
    'Password Hash' => 'Parol xash',
    'Password Repeat' => 'Parolni takrorlash',
    'Password Reset Token' => 'Parolni tiklash tokeni',
    'Paypal Order ID' => 'Paypal Buyurtma ID',
    'Please choose your new password:' => 'Iltimos, yangi parolni tanlang:',
    'Please contact us if you think this is server error. Thank you.' => 'Agar buni server xatosi deb hisoblasangiz, biz bilan bog`laning. Rahmat.',
    'Please fill out the following fields to login' => 'Kirish uchun quyidagi maydonlarni to`ldiring',
    'Please fill out the following fields to signup:' => 'Ro`yxatdan o`tish uchun quyidagi maydonlarni to`ldiring:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Iltimos, elektron pochtangizni to`ldiring. U erda parolni tiklash uchun havola yuboriladi.',
    'Please fill out your email. A verification email will be sent there.' => 'Iltimos, elektron pochtangizni to`ldiring. Tasdiqlash xati u yerga yuboriladi.',
    'Prev' => 'Oldingi',
    'Price' => 'Narx',
    'Product' => 'Mahsulot',
    'Product ID' => 'Mahsulot ID',
    'Product Image' => 'Mahsulot Rasmi',
    'Product Name' => 'Mahsulot Nomi',
    'Products' => 'Mahsulotlar',
    'Profile' => 'Profil',
    'Published' => 'Chop etilgan',
    'Quantity' => 'Soni',
    'Remember Me' => 'Remember Me',
    'Resend' => 'Qayta yuborish',
    'Save' => 'Saqlash',
    'Send' => 'Jo`natish',
    'Signup' => 'Ro`yxatdan o`tish',
    'State' => 'Shtat',
    'Status' => 'Ro`yxatdan o`tish',
    'Thanks for your business' => 'Biznesingiz uchun rahmat',
    'The above error occurred while the Web server was processing your request' => 'Yuqoridagi xatolik veb-server sizning so`rovingizga ishlov berayotganda yuz berdi',
    'There are no items in the cart' => 'Savatda hech qanday mahsulot yo`q',
    'Total Items' => 'Jami elementlar',
    'Total Price' => 'Umumiy narx',
    'Transaction ID' => 'Tranzaksiya ID',
    'Unit Price' => 'Donasining narxi',
    'Update' => 'Yangilash',
    'Update account' => 'Profilni Yangilash',
    'Update At' => 'Yangilangan vaqt',
    'Update By' => 'Tomonidan yangilangan',
    'Update_by' => 'Update_by',
    'User ID' => 'Foylanuvchi ID',
    'Username' => 'Foydalanuvchi nomi',
    'Verification Token' => 'Tasdiqlash tokeni',
    'Welcome {0}' => 'Xush kelibsiz {0}',
    'Your account successfully updated' => 'Hisobingiz muvaffaqiyatli yangilandi',
    'Your address successfully updated' => 'Manzilingiz muvaffaqiyatli yangilandi',
    'Your cart items' => 'Savatingiz buyumlari',
    'ZipCode' => 'Po`chta indeksi',
    'Zipcode' => 'Po`chta indeksi',
    'reset it' => 'uni qayta o`rnating',
];
